  - name: Install the packages Apache2 & PHP
    apk:
      name: apache2,php7-apache2
      state: latest
      update_cache: yes

  - name: Sets Up PHP Info Page
    copy:
      src: "./index.php"
      dest: "/var/www/localhost/htdocs/index.php"